# Generated by Django 4.0.6 on 2022-08-01 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('description', models.CharField(max_length=80)),
                ('plant', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=4)),
                ('unrestricted', models.IntegerField()),
                ('valueUnrestricted', models.IntegerField()),
                ('blocked', models.IntegerField()),
                ('price', models.FloatField()),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='products')),
            ],
        ),
    ]
