# Generated by Django 4.0.6 on 2022-08-02 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('model', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=50)),
                ('productivity', models.CharField(max_length=20)),
                ('shortDescr', models.CharField(max_length=100)),
                ('longDescr', models.TextField()),
                ('w_d_h', models.CharField(max_length=14)),
                ('w_d_h_packed', models.CharField(max_length=14)),
                ('weight', models.FloatField()),
                ('weight_packed', models.FloatField()),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.IntegerField()),
                ('blocked', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', to='wap.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='wap.product')),
            ],
        ),
    ]
