# Generated by Django 4.0.6 on 2022-08-02 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='productivity',
            field=models.CharField(max_length=50),
        ),
    ]
