# Generated by Django 4.0.6 on 2022-08-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wap', '0005_remove_price_id_remove_stock_id_alter_price_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_packed',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
